### ISSUE TITLE
TypeError: console.log is not a function

### ISSUE THREAD

**Issue by siclark** [fabio-looker/look-at-me-sideways#2]
I've been taking a look at this before we try setting it up as part of our CI and ran into the above error when trying to run LAMS locally (on a Windows machine). It seems that it's caused by the redefinition of `console` object from `index.js:37` as below:
```		
		const project = await parser.parseFiles({
			source: cliArgs.input || cliArgs.i,
			conditionalCommentString: 'LAMS',
			console: {
				warn: (msg) => lamsMessages.push({message: msg&&msg.message||msg, level: 'lams-warning'}), // LAMS warnings should not abort the deploy
				error: (msg) => lamsMessages.push({message: msg&&msg.message||msg, level: 'lams-error'}), // LAMS errors should abort the deploy
			},
		});
```

It seems that then the `lookml-parser` doesn't have a `console.log` method to call, hence the error. I fixed it (for my testing use case) by adding:
```
log: (msg) => console.log(msg)
```

I know this isn't a supported project and is designed to be run via Jenkins (I had to comment out some code related to that to get this to run from the command line) but thought I'd note this here, since I spent a bit of time working it out and someone else might benefit from finding this. No idea if it matters for the project under its intended usage, or if it's a weird node-on-windows thing or what!

Cheers.

P.S. you might not want to be exposing your Jenkins' location in `jobURL` 😉

**Comment by fabiocbinbutter** [comment]
Hi @siclark! Thanks for pointing it out. We are actually in the process of actively getting this ready for the first release. We accidentally pushed some of the changes to master before they were all ready and I didn't think anyone would start using it yet. In a week or two we will be announcing this as ready for broader use and will be addressing the above issues for sure. (Until then if you want a preview, you can also check out the release/1.0 branch)

**Comment by fabio-looker** [comment]
So, we still have some documentation changes to finish before the release, but they are not critical to functionality and master is already in an incomplete state, so I went ahead and merged our current changes into master, which should resolve all of the above (except the exposure of the job url)
